### ISSUE TITLE
How to update properly?

### ISSUE THREAD

**Issue by Kixunil** [alexcrichton/cargo-local-registry#5]
Currently, I can't use cargo update to pull new versions of crates if I use local registry, because it tries to use that registry. And since `cargo-local-registry` works with `Cargo.lock` it won't update on it's own.

For now, I've solved it by temporarily renaming `.cargo` directory but I believe there should be more straightforward method.

Am I missing something or is this a missing feature?

**Comment by alexcrichton** [comment]
Yeah currently to update crates you'll have to temporarily un-override and then re-override after you've re-vendored

**Comment by c4augustus** [comment]
Also commenting out the .cargo/config line "#replace-with = 'local-registry'" effectively toggles the local override between "cargo update; cargo local-registry --sync Cargo.lock ..." and normal cargo usage. Although it would be preferable to have a command option (--ignore-registry-replace?), this is a critical achievement. Not only can we work offline, but cargo builds are much faster using the local registry. Thanks for this.

**Comment by lilianmoraru** [comment]
@alexcrichton Any updates on this?
I am really considering pushing this at work(we are not allowed to touch the external Internet when building our code - security reasons and to allow 10 years later to be able to come to this version and have it always work the same way).
I was not able to bring Rust into our environment because it depends a lot on `crates.io` and the vendoring was painful before.

**Comment by alexcrichton** [comment]
This is possible nowadays, it'd need to copy [what's in `cargo vendor`](https://github.com/alexcrichton/cargo-vendor/blob/b544e5ad6ab1a41c4559f164a52af937bac45214/src/main.rs#L74-L85)

**Comment by idubrov** [comment]
See #80.
